"""Write pages/assets/og_card.png, the 1200x630 image X and every other platform
shows when someone shares the site.

WHY. Aaron picked X as the seeding channel (2026-07-29), and the site had no
Open Graph or Twitter card tags and no image of the right shape at all, so a shared
link rendered as a bare URL. The receipt notes we already generate are 1080x1350
portrait, built for the Substack feed; a link card wants roughly 1.91:1, so a
portrait image gets centre-cropped into nonsense.

THE FIGURES ARE READ, NEVER TYPED. Same rule as the receipt notes and for the same
reason: a social card is the most-seen and least-reviewed surface we own, so it is
exactly where a stale number would survive longest. If the log moves, this moves.

    python scripts/generate_og_card.py

Regenerated by the daily pipeline, so the card always matches the published record.
"""

import sys
from pathlib import Path

import pandas as pd
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
LOG_CSV = ROOT / "data/exports/prediction_tracking_honest.csv"
OUT = ROOT / "pages/assets/og_card.png"
BALL = ROOT / "pages/assets/logo_substack.png"

# 1200x630 is the size every platform documents for a large summary card. Twitter
# accepts 2:1, Facebook 1.91:1; 1200x630 satisfies both without a re-crop.
W, H = 1200, 630

# Origin palette, lifted from templates/origin.html so the card and the site agree.
OBSIDIAN = (15, 16, 17)
CLOUD = (245, 245, 247)
ASH = (159, 159, 160)
IRIS = (132, 125, 255)

# FONTS MUST RESOLVE ON BOTH HOSTS. This runs on Aaron's Windows PC by hand and on
# the Ubuntu VPS from cron, and the older receipt generator hardcodes C:/Windows/
# Fonts/, which simply does not exist there. Each role lists Windows first, then the
# DejaVu equivalents that ship with the VPS, and the first hit wins.
FONT_CANDIDATES = {
    "mono": ["C:/Windows/Fonts/consola.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"],
    "mono_bold": ["C:/Windows/Fonts/consolab.ttf",
                  "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"],
    "serif_bold": ["C:/Windows/Fonts/georgiab.ttf",
                   "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"],
    "sans": ["C:/Windows/Fonts/segoeui.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
}


def _font(role: str, sz: int):
    for path in FONT_CANDIDATES[role]:
        if Path(path).exists():
            return ImageFont.truetype(path, sz)
    sys.exit(f"no font available for {role!r}; tried {FONT_CANDIDATES[role]}")


def mono(sz, bold=False):
    return _font("mono_bold" if bold else "mono", sz)


def serif(sz):
    # DM Serif Display is a webfont we do not ship. Georgia on Windows, DejaVu Serif
    # on the VPS; this renders once into a PNG so the substitution is invisible.
    return _font("serif_bold", sz)


def sans(sz):
    return _font("sans", sz)


def figures() -> tuple[float, int]:
    if not LOG_CSV.exists():
        sys.exit(f"missing {LOG_CSV}; cannot build a card without the record")
    d = pd.read_csv(LOG_CSV).dropna(subset=["correct"])
    if not len(d):
        sys.exit("honest log has no graded rows")
    return 100 * d["correct"].mean(), len(d)


def main() -> None:
    acc, n = figures()

    img = Image.new("RGB", (W, H), OBSIDIAN)
    d = ImageDraw.Draw(img)

    # A single iris hairline along the top, the one brand flourish the site uses.
    d.rectangle([0, 0, W, 5], fill=IRIS)

    # Wordmark
    d.text((72, 74), "SECOND BOUNCE", font=mono(30, bold=True), fill=ASH)

    # The claim. This is the whole point of the card: the number, at the size that
    # survives a timeline scroll at thumbnail scale.
    d.text((72, 138), f"{acc:.1f}%", font=serif(168), fill=CLOUD)

    label = "of NBA games called correctly"
    d.text((78, 330), label, font=sans(42), fill=CLOUD)

    # The qualifier, which is the actual differentiator. Anyone can claim a number;
    # the sample and the method are what make it checkable.
    d.text((78, 392), f"across {n:,} games, every pick logged before tip-off",
           font=sans(31), fill=ASH)

    # Receipt strip, monospace, mirroring the site's {{RECEIPT}} block. It stops
    # short of the ball rather than running its border underneath it.
    strip_y = 486
    d.rectangle([72, strip_y, 952, strip_y + 66], outline=(46, 46, 46), width=2)
    d.text((96, strip_y + 20),
           f"[ {acc:.1f}% · {n:,} games · verified walk-forward ]",
           font=mono(27), fill=IRIS)

    # The ball, bottom right, cropped to a disc.
    if BALL.exists():
        with Image.open(BALL) as ball:
            size = 132
            b = ball.convert("RGBA").resize((size, size))
            mask = Image.new("L", (size, size), 0)
            ImageDraw.Draw(mask).ellipse([0, 0, size - 1, size - 1], fill=255)
            img.paste(b, (W - size - 72, H - size - 66), mask)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT, "PNG", optimize=True)
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT)}  {W}x{H}  {kb:.0f}KB  ({acc:.2f}%, n={n})")
    if kb > 5120:
        print("WARNING: over 5MB, X will refuse to render it")


if __name__ == "__main__":
    main()
